name = "Aion"

authority="cpan:DART"
license="gpl_3"

badges = ["github-actions/test.yml", "metacpan", "coveralls"]
markdown_maker = "Liveman::MinillaPod2Markdown"
module_maker="ModuleBuildTiny"
static_install = "auto"

[test_coverage]
coverage_tool = "Devel::Cover"
