name = "Aion"

authority="cpan:DART"
license="gpl_3"

badges = ["github-actions/test.yml", "metacpan", "codecov"]
markdown_maker = "Liveman::MinillaPod2Markdown"
module_maker="ModuleBuildTiny"
static_install = "auto"

[resources]
coverage = "https://codecov.io/gh/darviarush/perl-aion"
