name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ["5.40", "5.38", "5.36", "5.34", "5.32", "5.30", "5.28", "5.26", "5.24", "5.22"]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-recommends .
      - name: Install Devel::Cover
        run: cpanm -n Devel::Cover
      - name: Run test with coverage
        env:
          PERL5OPT: -MDevel::Cover
        run: |
          prove -lr t
          env -u PERL5OPT cover --report lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: cover_db/lcov/lcov.info
